#!/bin/sh
# Copyright (C) Juewuy

[ -z "$SBOX_DIR" ] && .sbox_ctl init
INT=$(sbox get sbox.interval)
[ -z "$INT" ] && INT=5

if [ -z "$boot" ];then
	for service in $SBOX_DIR/config/boot.list;do
		sh $SBOX_DIR/tools/scripts/$service boot >/dev/null
	done
	boot=1
fi

while [ -z "$1" ];do
	#检测并守护各个服务的状态
	for service in $SBOX_DIR/config/service.list;do
		[ -z "$(pidof $app)" ] && sh $SBOX_DIR/service.sh start $service
	done
	sleep $INT
done

exit 0
